version: '3'
services:
  mlflow-server:
    build : .
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
    env_file: .devcontainer/devcontainer.env
    volumes:
      - .:/mlflow
    restart: always
