version: '3'
services:
  mlflow-server:
    build : .
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
    volumes:
      - ./mlflow-data:/mlflow-data
      - ../mlflow-server-devcontainer:/workspace/mlflow-server-devcontainer
    restart: always
